common:
  encrypt:
    password: ${ENCRYPTION_PASSWORD:lowcoder.org}
    salt: ${ENCRYPTION_SALT:lowcoder.org}
  security:
    corsAllowedDomainString: ${CORS_ALLOWED_DOMAINS:*}
  workspace:
    mode: ENTERPRISE

auth:
  api-key:
    secret: ${LOWCODER_API_KEY_SECRET:123456789101112131415123456789101112131415123456789101112131415123456789101112131415}
  email:
    enable: ${LOGIN_CHANNEL_EMAIL:true}
    enable-register: ${ENABLE_USER_SIGN_UP:true}
  workspace-creation: ${LOWCODER_CREATE_SIGNUP_WORKSPACE:true}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/lowcoder?socketTimeoutMS=5000}
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
